name: Build on Main Branch

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Build Release App (APK & AAB)
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Decode Keystore
        id: decode_keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
          KEYSTORE_PATH="${{ runner.temp }}/keystore.jks"
          echo "keystore_path=$KEYSTORE_PATH" >> $GITHUB_OUTPUT
          echo $KEYSTORE_BASE64 | base64 --decode > $KEYSTORE_PATH

      - name: Grant Execute Permission to gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle (APK and AAB)
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
          SIGNING_STORE_FILE: ${{ steps.decode_keystore.outputs.keystore_path }}
        run: ./gradlew assembleRelease bundleRelease

      - name: Create GitHub Pre-release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            app/build/outputs/apk/release/*.apk
            app/build/outputs/bundle/release/*.aab
          tag_name: build-${{ github.sha }}
          name: "Build ${{ github.sha }}"